language: node_js
node_js: node

notifications:
  email: false

branches:
  except:
    - /^v\d+\.\d+\.\d+$/

before_script: npm prune
script:
  - yarn build
  - yarn lint
  - yarn test
after_success:
  - yarn semantic-release
